defaults:
  - _self_
  - data: [default]
  - models: [default]
  - setup: [default]




verbose: True
log_wandb: True

description: "Primer entrenament amb train i validació, esperem que tot vagi bé."
run_name: "First Training 25 ephocs"
task: "attribute graph construction"

