defaults:
  - _self_
  - data: [default]
  - models: [default]
  - setup: [default]




verbose: True
log_wandb: True
name_checkpoint: "less_complexity_more_family_messages"

description: "Experiments amb menys complexitat que sembla que són els que millor funcionen"
run_name: "Redoing the message passing with familis, solved bug"
task: "attribute graph construction"



