

line_encoder:
  kernel_height: ???
  kernel_width: ???
  hidden_channels: 64
  output_channels: 128
  num_hidden_convolutions: 3


edge_encoder:
  kernel_height: ${models.line_encoder.kernel_height}
  kernel_width: ${models.line_encoder.kernel_width}
  hidden_channels: 64
  edge_embedding_size: 128
  number_of_entities: 5


gnn_encoder:
  attributes: ???
  embedding_size: 128
  aggr: "mean"

kernel_ratio : 0.7

